import { explorerImage } from '../features/darshan/data/images'

export type CrowdLevel = 'low' | 'moderate' | 'high' | 'very-high'
export type DarshanTag = 'free' | 'paid'
export type TempleBadge = 'must-visit' | 'popular' | 'sacred'
export type RegionFilterId =
  | 'all'
  | 'by-region'
  | 'tirumala'
  | 'tirupati-town'
  | 'intermediate'
  | 'extended'
  | 'telangana-circuit'

export type TempleListing = {
  id: string
  slug: string
  name: string
  city: string
  state: string
  region: string
  regionKey: RegionFilterId
  circuit: string
  rating: number
  crowd: CrowdLevel
  distanceKm: number
  distanceLabel: string
  darshan: DarshanTag
  badge?: TempleBadge
  mustVisit?: boolean
  imageUrl: string
  imageAlt: string
  description: string
  openTime: string
  closeTime: string
  tags: string[]
}

export const REGION_FILTERS: { id: RegionFilterId; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'by-region', label: 'By Region' },
  { id: 'tirumala', label: 'Tirumala' },
  { id: 'tirupati-town', label: 'Tirupati Town' },
  { id: 'intermediate', label: 'Intermediate' },
  { id: 'extended', label: 'Extended' },
  { id: 'telangana-circuit', label: 'Telangana Circuit' },
]

export const TEMPLE_LISTINGS: TempleListing[] = [
  {
    id: 't1',
    slug: 'sri-venkateswara-tirumala',
    name: 'Sri Venkateswara Temple',
    city: 'Tirumala',
    state: 'Andhra Pradesh',
    region: 'Tirumala',
    regionKey: 'tirumala',
    circuit: 'South India',
    rating: 4.9,
    crowd: 'very-high',
    distanceKm: 0,
    distanceLabel: '0 km from Tirupati hub',
    darshan: 'paid',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t1'),
    imageAlt: 'Tirumala temple',
    description: 'Sacred hill shrine of Lord Venkateswara — among the most visited temples in the world.',
    openTime: '3:00 AM',
    closeTime: '11:00 PM',
    tags: ['Must Visit', 'Special Entry'],
  },
  {
    id: 't2',
    slug: 'padmavathi-tiruchanur',
    name: 'Sri Padmavathi Ammavari Temple',
    city: 'Tiruchanur',
    state: 'Andhra Pradesh',
    region: 'Tirupati Town',
    regionKey: 'tirupati-town',
    circuit: 'South India',
    rating: 4.7,
    crowd: 'moderate',
    distanceKm: 5,
    distanceLabel: '5 km from Tirupati',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t2'),
    imageAlt: 'Padmavathi temple',
    description: 'Consort temple of Goddess Padmavathi — often visited before Tirumala darshan.',
    openTime: '5:00 AM',
    closeTime: '9:00 PM',
    tags: ['Popular'],
  },
  {
    id: 't3',
    slug: 'govindaraja-tirupati',
    name: 'Sri Govindaraja Swamy Temple',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    region: 'Tirupati Town',
    regionKey: 'tirupati-town',
    circuit: 'South India',
    rating: 4.6,
    crowd: 'moderate',
    distanceKm: 2,
    distanceLabel: '2 km from Tirupati',
    darshan: 'free',
    imageUrl: explorerImage('t3'),
    imageAlt: 'Govindaraja temple',
    description: 'Historic Vaishnavite temple in Tirupati town with ornate gopuram architecture.',
    openTime: '5:30 AM',
    closeTime: '9:00 PM',
    tags: ['Sacred'],
  },
  {
    id: 't4',
    slug: 'kapileswara-tirupati',
    name: 'Sri Kapileswara Swamy Temple',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    region: 'Tirupati Town',
    regionKey: 'tirupati-town',
    circuit: 'South India',
    rating: 4.5,
    crowd: 'low',
    distanceKm: 3,
    distanceLabel: '3 km from Tirupati',
    darshan: 'free',
    badge: 'sacred',
    imageUrl: explorerImage('t4'),
    imageAlt: 'Kapileswara temple',
    description: 'Ancient Shiva temple at the foot of Tirumala hills with a sacred waterfall.',
    openTime: '6:00 AM',
    closeTime: '8:30 PM',
    tags: ['Sacred'],
  },
  {
    id: 't5',
    slug: 'kalahasti',
    name: 'Sri Kalahasti Temple',
    city: 'Srikalahasti',
    state: 'Andhra Pradesh',
    region: 'Intermediate',
    regionKey: 'intermediate',
    circuit: 'South India',
    rating: 4.8,
    crowd: 'high',
    distanceKm: 38,
    distanceLabel: '38 km from Tirupati',
    darshan: 'free',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t5'),
    imageAlt: 'Kalahasti temple',
    description: 'Pancha Bhoota Sthalam representing Vayu (air) — famous for Rahu-Ketu puja.',
    openTime: '5:00 AM',
    closeTime: '9:00 PM',
    tags: ['Must Visit', 'Puja'],
  },
  {
    id: 't6',
    slug: 'kanipakam',
    name: 'Sri Varasidhi Vinayaka Temple',
    city: 'Kanipakam',
    state: 'Andhra Pradesh',
    region: 'Intermediate',
    regionKey: 'intermediate',
    circuit: 'South India',
    rating: 4.6,
    crowd: 'moderate',
    distanceKm: 75,
    distanceLabel: '75 km from Tirupati',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t6'),
    imageAlt: 'Kanipakam temple',
    description: 'Self-manifested Ganesha idol — growing in size over centuries per local belief.',
    openTime: '4:00 AM',
    closeTime: '9:30 PM',
    tags: ['Popular'],
  },
  {
    id: 't7',
    slug: 'srisailam',
    name: 'Sri Mallikarjuna Swamy Temple',
    city: 'Srisailam',
    state: 'Andhra Pradesh',
    region: 'Telangana Circuit',
    regionKey: 'telangana-circuit',
    circuit: 'South India',
    rating: 4.8,
    crowd: 'high',
    distanceKm: 210,
    distanceLabel: '210 km from Tirupati',
    darshan: 'free',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t7'),
    imageAlt: 'Srisailam temple',
    description: 'Jyotirlinga and Shakti Peetha on the banks of Krishna river in Nallamala hills.',
    openTime: '4:30 AM',
    closeTime: '10:00 PM',
    tags: ['Must Visit', 'Jyotirlinga'],
  },
  {
    id: 't8',
    slug: 'yadadri',
    name: 'Sri Lakshmi Narasimha Swamy Temple',
    city: 'Yadadri',
    state: 'Telangana',
    region: 'Telangana Circuit',
    regionKey: 'telangana-circuit',
    circuit: 'South India',
    rating: 4.7,
    crowd: 'moderate',
    distanceKm: 280,
    distanceLabel: '280 km from Tirupati',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t8'),
    imageAlt: 'Yadadri temple',
    description: 'Newly renovated hill temple near Hyderabad — popular weekend pilgrimage.',
    openTime: '4:00 AM',
    closeTime: '9:30 PM',
    tags: ['Popular'],
  },
  {
    id: 't9',
    slug: 'shirdi-sai-baba',
    name: 'Sai Baba Temple',
    city: 'Shirdi',
    state: 'Maharashtra',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'West India',
    rating: 4.8,
    crowd: 'high',
    distanceKm: 420,
    distanceLabel: '420 km from hub',
    darshan: 'free',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t9'),
    imageAlt: 'Shirdi temple',
    description: 'Samadhi mandir of Sai Baba — one of India\'s most visited pilgrimage sites.',
    openTime: '4:00 AM',
    closeTime: '11:00 PM',
    tags: ['Must Visit'],
  },
  {
    id: 't10',
    slug: 'shani-shingnapur',
    name: 'Shani Shingnapur Temple',
    city: 'Shingnapur',
    state: 'Maharashtra',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'West India',
    rating: 4.4,
    crowd: 'moderate',
    distanceKm: 480,
    distanceLabel: '480 km from hub',
    darshan: 'free',
    imageUrl: explorerImage('t10'),
    imageAlt: 'Shani Shingnapur',
    description: 'Open-air shrine to Lord Shani — unique village with no door locks tradition.',
    openTime: '5:00 AM',
    closeTime: '10:00 PM',
    tags: ['Sacred'],
  },
  {
    id: 't11',
    slug: 'vaishno-devi',
    name: 'Vaishno Devi Shrine',
    city: 'Katra',
    state: 'Jammu & Kashmir',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'North India',
    rating: 4.9,
    crowd: 'very-high',
    distanceKm: 2100,
    distanceLabel: '2,100 km from hub',
    darshan: 'free',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t11'),
    imageAlt: 'Vaishno Devi',
    description: 'Cave shrine in Trikuta mountains — 12 km trek from Katra base camp.',
    openTime: '24 hours',
    closeTime: '24 hours',
    tags: ['Must Visit', 'Trek'],
  },
  {
    id: 't12',
    slug: 'golden-temple',
    name: 'Harmandir Sahib (Golden Temple)',
    city: 'Amritsar',
    state: 'Punjab',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'North India',
    rating: 4.9,
    crowd: 'high',
    distanceKm: 1950,
    distanceLabel: '1,950 km from hub',
    darshan: 'free',
    badge: 'sacred',
    imageUrl: explorerImage('t12'),
    imageAlt: 'Golden Temple',
    description: 'Holiest Gurdwara with gold-plated sanctum surrounded by the Amrit Sarovar.',
    openTime: '24 hours',
    closeTime: '24 hours',
    tags: ['Sacred'],
  },
  {
    id: 't13',
    slug: 'jagannath-puri',
    name: 'Jagannath Temple',
    city: 'Puri',
    state: 'Odisha',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'East India',
    rating: 4.6,
    crowd: 'high',
    distanceKm: 680,
    distanceLabel: '680 km from hub',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t13'),
    imageAlt: 'Jagannath temple',
    description: 'Char Dham temple famous for Rath Yatra and Mahaprasad.',
    openTime: '5:00 AM',
    closeTime: '10:00 PM',
    tags: ['Popular', 'Char Dham'],
  },
  {
    id: 't14',
    slug: 'lingaraj-bhubaneswar',
    name: 'Lingaraj Temple',
    city: 'Bhubaneswar',
    state: 'Odisha',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'East India',
    rating: 4.5,
    crowd: 'moderate',
    distanceKm: 720,
    distanceLabel: '720 km from hub',
    darshan: 'free',
    imageUrl: explorerImage('t14'),
    imageAlt: 'Lingaraj temple',
    description: '11th-century Shiva temple — finest example of Kalinga architecture.',
    openTime: '6:00 AM',
    closeTime: '9:00 PM',
    tags: ['Sacred'],
  },
  {
    id: 't15',
    slug: 'guruvayur',
    name: 'Guruvayur Temple',
    city: 'Guruvayur',
    state: 'Kerala',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'South India',
    rating: 4.7,
    crowd: 'moderate',
    distanceKm: 520,
    distanceLabel: '520 km from hub',
    darshan: 'paid',
    badge: 'popular',
    imageUrl: explorerImage('t15'),
    imageAlt: 'Guruvayur temple',
    description: 'Dwarka of the South — Krishna temple with strict dress code for devotees.',
    openTime: '3:00 AM',
    closeTime: '9:15 PM',
    tags: ['Popular'],
  },
  {
    id: 't16',
    slug: 'sabarimala',
    name: 'Sabarimala Ayyappa Temple',
    city: 'Pathanamthitta',
    state: 'Kerala',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'South India',
    rating: 4.8,
    crowd: 'very-high',
    distanceKm: 580,
    distanceLabel: '580 km from hub',
    darshan: 'free',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t16'),
    imageAlt: 'Sabarimala',
    description: 'Hill shrine open during Mandalam season — 41-day vratham tradition.',
    openTime: 'Seasonal',
    closeTime: 'Seasonal',
    tags: ['Must Visit', 'Seasonal'],
  },
  {
    id: 't17',
    slug: 'kashi-vishwanath',
    name: 'Kashi Vishwanath Temple',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'North India',
    rating: 4.8,
    crowd: 'very-high',
    distanceKm: 1450,
    distanceLabel: '1,450 km from hub',
    darshan: 'paid',
    badge: 'must-visit',
    mustVisit: true,
    imageUrl: explorerImage('t17'),
    imageAlt: 'Kashi Vishwanath',
    description: 'Jyotirlinga on the Ganges — spiritual heart of Hindu pilgrimage.',
    openTime: '3:00 AM',
    closeTime: '11:00 PM',
    tags: ['Must Visit', 'Jyotirlinga'],
  },
  {
    id: 't18',
    slug: 'iskcon-vrindavan',
    name: 'ISKCON Temple Vrindavan',
    city: 'Vrindavan',
    state: 'Uttar Pradesh',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'North India',
    rating: 4.6,
    crowd: 'moderate',
    distanceKm: 1480,
    distanceLabel: '1,480 km from hub',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t18'),
    imageAlt: 'ISKCON Vrindavan',
    description: 'Grand Krishna temple with evening aarti and prasadam distribution.',
    openTime: '4:30 AM',
    closeTime: '8:45 PM',
    tags: ['Popular'],
  },
  {
    id: 't19',
    slug: 'somnath',
    name: 'Somnath Temple',
    city: 'Veraval',
    state: 'Gujarat',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'West India',
    rating: 4.7,
    crowd: 'moderate',
    distanceKm: 1100,
    distanceLabel: '1,100 km from hub',
    darshan: 'free',
    badge: 'sacred',
    imageUrl: explorerImage('t19'),
    imageAlt: 'Somnath temple',
    description: 'First among twelve Jyotirlingas on the shores of the Arabian Sea.',
    openTime: '6:00 AM',
    closeTime: '10:00 PM',
    tags: ['Sacred', 'Jyotirlinga'],
  },
  {
    id: 't20',
    slug: 'meenakshi-madurai',
    name: 'Meenakshi Amman Temple',
    city: 'Madurai',
    state: 'Tamil Nadu',
    region: 'Extended',
    regionKey: 'extended',
    circuit: 'South India',
    rating: 4.8,
    crowd: 'high',
    distanceKm: 420,
    distanceLabel: '420 km from hub',
    darshan: 'free',
    badge: 'popular',
    imageUrl: explorerImage('t20'),
    imageAlt: 'Meenakshi temple',
    description: 'Iconic Dravidian temple complex with towering colourful gopurams.',
    openTime: '5:00 AM',
    closeTime: '10:00 PM',
    tags: ['Popular', 'Architecture'],
  },
]

export const REGIONS = [
  'Tirumala',
  'Tirupati Town',
  'Intermediate',
  'Telangana Circuit',
  'Extended',
] as const

export const CROWD_LABELS: Record<CrowdLevel, string> = {
  low: 'Low crowd',
  moderate: 'Moderate crowd',
  high: 'High crowd',
  'very-high': 'Very High crowd',
}

export const BADGE_LABELS: Record<TempleBadge, string> = {
  'must-visit': 'Must Visit',
  popular: 'Popular',
  sacred: 'Sacred',
}

export function filterTemplesByRegion(filter: RegionFilterId): TempleListing[] {
  if (filter === 'all' || filter === 'by-region') return TEMPLE_LISTINGS
  return TEMPLE_LISTINGS.filter((t) => t.regionKey === filter)
}

export function groupTemplesByRegion(temples: TempleListing[]): Map<string, TempleListing[]> {
  const map = new Map<string, TempleListing[]>()
  for (const t of temples) {
    const list = map.get(t.region) ?? []
    list.push(t)
    map.set(t.region, list)
  }
  return map
}
